(() => {
  'use strict';
  const app = document.querySelector('#app');
  const route = location.hash ? `/${location.hash.slice(1)}` : (location.pathname.replace(/\/$/, '') || '/');
  const eur = n => typeof n === 'number' ? new Intl.NumberFormat('en-IE', {style:'currency',currency:'EUR',maximumFractionDigits:0}).format(n) : 'Not quantified';
  const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const line = (label, amount, negative=false) => `<tr><td>${label}</td><td class="num">${negative?'(':''}${eur(amount)}${negative?')':''}</td></tr>`;
  const total = (label, amount) => `<tr class="total"><th>${label}</th><th class="num">${eur(amount)}</th></tr>`;
  const table = (head, rows) => `<div class="table-scroll"><table class="report-table"><thead>${head}</thead><tbody>${rows}</tbody></table></div>`;
  const badge = v => `<span class="status ${String(v).replace(/_/g,'-').replace(/ /g,'-')}">${esc(String(v).replace(/_/g,' '))}</span>`;
  const notice = () => `<aside class="basis-notice"><b>Primary statement basis: €65,000 evidence-qualified reconstruction.</b> The statements use €405,000 COGS and €112,000 flow-derived inventory. The €121,000 physical-count alternative is direct evidence but differs by €9,000; it is disclosed, not silently posted.</aside>`;
  const confirmation = d => `<section class="panel review-confirmation"><p class="eyebrow">Student review confirmation</p><h2>${esc(d.studentReviewConfirmation.name)} · ${esc(d.studentReviewConfirmation.id)}</h2><p>${esc(d.studentReviewConfirmation.text)}</p></section>`;

  function activeNav() {
    document.querySelectorAll('nav a').forEach(a => {
      const destination = a.getAttribute('href');
      a.classList.toggle('active', (route === '/' && destination === '#') || destination === `#${route.slice(1)}`);
    });
  }

  function home(d) {
    const b = d.statements.balanceSheet;
    return `${notice()}<section class="metrics"><article class="metric-card"><span>Quantified profit</span><strong>${eur(65000)}</strong><small>evidence-qualified</small></article><article class="metric-card"><span>Closing cash</span><strong>${eur(60000)}</strong><small>bank-supported</small></article><article class="metric-card"><span>Primary inventory</span><strong>${eur(112000)}</strong><small>flow-derived basis</small></article><article class="metric-card warning"><span>Open differences</span><strong>€9k + €45k</strong><small>not journalled</small></article></section><section class="content-grid two-columns"><article class="panel"><p class="eyebrow">Board conclusion</p><h2>Correct the evidence, not the result.</h2><p>${esc(d.boardRecommendation.text)}</p><p>The primary balance sheet is internally consistent: ${eur(b.totalAssets)} assets = ${eur(b.totalLiabilities)} liabilities + ${eur(b.primaryResidualEquity)} residual equity.</p></article><article class="panel"><p class="eyebrow">Case-file map</p><ol class="compact-list"><li><a href="#statements">Statements</a> use one primary basis.</li><li><a href="#schedules">Schedules</a> trace each total.</li><li><a href="#reconciliations">Controls</a> show passes and qualifications.</li><li><a href="#decisions">Decision register</a> exposes all 100 answers.</li></ol></article></section><section class="panel"><p class="eyebrow">Principal qualification</p><h2>€112,000 or €121,000 closing inventory?</h2><div class="comparison"><div><b>Primary reporting basis</b><strong>${eur(112000)}</strong><span>€80k opening + €459k purchases − €405k COGS − €22k damage</span></div><div><b>Physical-count alternative</b><strong>${eur(121000)}</strong><span>€143k count − €22k damaged stock</span></div><div><b>Unresolved difference</b><strong>${eur(9000)}</strong><span>No cause identified; no adjusting journal created</span></div></div></section>${confirmation(d)}`;
  }

  function statements(d) {
    const p=d.statements.profitAndLoss, c=d.statements.cashFlow, b=d.statements.balanceSheet, s=d.schedules;
    const grossProfit=p.revenue-p.productCOGS-p.damagedInventoryWriteOff-p.directEventPayroll;
    const operatingProfit=grossProfit-p.salesPayroll-p.officePayroll-p.rent-p.marketing-p.software-p.utilities-p.repairAndCalibration-p.depreciation-p.badDebtImpairment-p.legalProvision;
    const currentAssets=b.cash+s.revenueAndReceivables.grossTradeReceivables-s.revenueAndReceivables.R17Impairment+b.inventoryPrimaryFlowBasis;
    const pnl=table('<tr><th>Profit &amp; loss</th><th class="num">1 Jan – 31 Aug 2026 · EUR</th></tr>',line('Revenue',p.revenue)+line('Materials consumed',p.productCOGS,true)+line('Damaged inventory impairment',p.damagedInventoryWriteOff,true)+line('Direct event payroll',p.directEventPayroll,true)+total('Gross profit',grossProfit)+line('Selling payroll',p.salesPayroll,true)+line('Administration payroll',p.officePayroll,true)+line('Rent',p.rent,true)+line('Marketing',p.marketing,true)+line('Software',p.software,true)+line('Utilities',p.utilities,true)+line('Repairs',p.repairAndCalibration,true)+line('Depreciation — amount supported; useful lives incomplete',p.depreciation,true)+line('Receivable impairment — known minimum',p.badDebtImpairment,true)+line('Legal provision expense',p.legalProvision,true)+total('Operating profit',operatingProfit)+line('Interest expense',p.interestExpense,true)+total('Conditional profit before unquantified items',p.quantifiedProfit));
    const cash=table('<tr><th>Cash flow</th><th class="num">1 Jan – 31 Aug 2026 · direct method · EUR</th></tr>',line('Customer receipts',c.customerReceipts)+line('Supplier payments',Math.abs(c.supplierPayments),true)+line('Payroll payments',Math.abs(c.payrollPayments),true)+line('Rent',Math.abs(c.rentPayments),true)+line('Marketing',Math.abs(c.marketingPayments),true)+line('Software',Math.abs(c.softwarePayments),true)+line('Utilities',Math.abs(c.utilityPayments),true)+line('Repairs',Math.abs(c.repairPayments),true)+line('Interest paid — operating policy',Math.abs(c.interestPaid),true)+total('Net operating cash flow',c.operating)+line('Packaging machine',60000,true)+line('Photo booth',20000,true)+total('Net investing cash flow',c.investing)+line('New borrowing',50000)+line('Principal repaid',19000,true)+line('Owner payments — distribution convention',110000,true)+total('Net financing cash flow',c.financingOwner)+total('Net cash movement',c.operating+c.investing+c.financingOwner)+line('Opening cash',c.openingCash)+total('Closing cash',c.closingCash));
    const bs=table('<tr><th>Balance sheet</th><th class="num">As at 31 Aug 2026 · EUR</th></tr>',line('Cash',b.cash)+line('Gross receivables',s.revenueAndReceivables.grossTradeReceivables)+line('Known credit-loss allowance',s.revenueAndReceivables.R17Impairment,true)+line('Inventory',b.inventoryPrimaryFlowBasis)+total('Current assets',currentAssets)+line('PPE at cost',s.ppeAndDepreciation.closingPPECost)+line('Accumulated depreciation — includes €24,000 period depreciation',s.ppeAndDepreciation.closingAccumulatedDepreciation,true)+total('Net PPE',b.ppeNet)+total('Total assets',b.totalAssets)+line('Trade payables',b.tradePayables)+line('Payroll payable',b.payrollPayable)+line('Contract liabilities',b.contractLiabilities)+line('Loan principal — maturity split unavailable',b.bankLoan)+line('Interest payable',b.interestPayable)+line('Legal provision',b.legalProvision)+total('Total liabilities',b.totalLiabilities)+line('Opening equity — inferred',s.equityAndDistributions.impliedOpeningEquityForRollForward)+line('Period conditional profit',p.quantifiedProfit)+line('Owner distributions — provisional',s.equityAndDistributions.totalDistributions,true)+total('Closing equity',b.primaryResidualEquity)+total('Liabilities and equity',b.totalLiabilitiesAndEquity));
    return `<section class="statement-basis"><span>Inventory basis for the displayed statements</span><b>Stated consumption · €405k consumed / €112k stock</b></section><section class="statement-stack statement-pack"><article class="panel statement-panel">${pnl}</article><article class="panel statement-panel">${cash}</article><article class="panel statement-panel">${bs}</article></section><section class="panel open-items"><h3>Unquantified items remain open</h3><p>No insurance expense or prepaid asset is recognised without reliable policy evidence. The €9,000 inventory count-to-flow difference, €45,000 supplier/AP difference and incomplete opening-balance support remain visible and unposted.</p></section>`;
  }

  function schedules(d) {
    const s=d.schedules;
    const ar=table('<tr><th>Completed-contract revenue and receivables</th><th class="num">EUR</th></tr>',line('NorthStar',s.revenueAndReceivables.NorthStarRevenue)+line('Freedom',s.revenueAndReceivables.FreedomRevenue)+line('Phoenix',s.revenueAndReceivables.PhoenixRevenue)+line('Liberty',s.revenueAndReceivables.LibertyRevenue)+total('Completed August revenue',s.revenueAndReceivables.totalRevenue)+line('Gross trade receivables',s.revenueAndReceivables.grossTradeReceivables)+line('Less: R-17 impairment',s.revenueAndReceivables.R17Impairment,true)+total('Net trade receivables',s.revenueAndReceivables.netTradeReceivables)+line('September customer deposits — liability',s.revenueAndReceivables.customerDeposits));
    const inv=table('<tr><th>Inventory and COGS schedule</th><th class="num">EUR</th></tr>',line('Opening inventory',s.inventoryAndCOGS.openingInventory)+line('Purchases',s.inventoryAndCOGS.purchases)+line('Less: primary materials consumed / COGS',s.inventoryAndCOGS.primaryMaterialsConsumedCOGS,true)+line('Less: damaged-stock write-off',s.inventoryAndCOGS.damagedInventoryWriteOff,true)+total('Primary flow-derived closing inventory',s.inventoryAndCOGS.primaryFlowClosingInventory)+'<tr class="section-row"><th colspan="2">Physical-count alternative (not posted)</th></tr>'+line('Physical/system count',s.inventoryAndCOGS.physicalSystemCount)+line('Less: damaged stock',s.inventoryAndCOGS.lessDamagedStock,true)+total('Count-based inventory alternative',s.inventoryAndCOGS.physicalCountAlternative)+line('Unresolved count-to-flow difference',s.inventoryAndCOGS.unresolvedDifference));
    const payroll=table('<tr><th>Payroll schedule</th><th class="num">EUR</th></tr>',line('Opening payroll payable',s.payroll.openingPayrollPayable)+line('Direct event payroll / cost of sales',s.payroll.directEventPayroll)+line('Sales payroll',s.payroll.salesPayroll)+line('Office payroll',s.payroll.officePayroll)+total('Total payroll expense',s.payroll.totalPayrollExpense)+line('Cash paid',s.payroll.cashPaid,true)+total('Closing payroll payable',s.payroll.closingPayrollAccrual));
    const ppe=table('<tr><th>PPE and depreciation schedule</th><th class="num">EUR</th></tr>',line('Opening PPE cost',s.ppeAndDepreciation.openingPPECost)+line('Packaging machine addition',s.ppeAndDepreciation.packagingMachineAddition)+line('Photo booth addition',s.ppeAndDepreciation.photoBoothAddition)+total('Closing PPE cost',s.ppeAndDepreciation.closingPPECost)+line('Opening accumulated depreciation',s.ppeAndDepreciation.openingAccumulatedDepreciation)+line('Period depreciation',s.ppeAndDepreciation.periodDepreciation)+total('Closing accumulated depreciation',s.ppeAndDepreciation.closingAccumulatedDepreciation)+total('Net PPE',s.ppeAndDepreciation.netPPE));
    const debt=table('<tr><th>Debt and interest schedule</th><th class="num">EUR</th></tr>',line('Opening loan',s.debtAndInterest.openingLoan)+line('New bank advance',s.debtAndInterest.newBankAdvance)+line('Principal repaid',s.debtAndInterest.principalRepaid,true)+total('Closing loan',s.debtAndInterest.closingLoan)+line('Interest expense',s.debtAndInterest.interestExpense)+line('Interest paid',s.debtAndInterest.interestPaid,true)+total('Interest payable',s.debtAndInterest.interestPayable));
    const equity=table('<tr><th>Equity and distributions schedule</th><th class="num">EUR</th></tr>',line('Owner villa distribution',s.equityAndDistributions.ownerVillaDistribution)+line('Owner-card distribution',s.equityAndDistributions.ownerCardDistribution)+total('Total distributions',s.equityAndDistributions.totalDistributions)+line('Primary residual closing equity',s.equityAndDistributions.primaryClosingEquity)+line('Implied opening equity for roll-forward only',s.equityAndDistributions.impliedOpeningEquityForRollForward));
    return `${notice()}<section class="page-heading"><p class="eyebrow">Traceable support</p><h2>Supporting schedules</h2><p>Every statement total is traced without treating an unresolved difference as an adjustment.</p></section><section class="schedule-grid"><article class="panel">${ar}</article><article class="panel">${inv}<p class="footnote">${esc(s.inventoryAndCOGS.qualification)}</p></article><article class="panel">${payroll}<p class="footnote">${esc(s.payroll.basis)}</p></article><article class="panel">${ppe}<p class="footnote">${esc(s.ppeAndDepreciation.basis)}</p></article><article class="panel">${debt}</article><article class="panel">${equity}<p class="footnote">${esc(s.equityAndDistributions.basis)}</p></article></section>`;
  }

  function evidence() {
    const items=[['Bank export','02 Bank Export August.csv','Closing cash €60,000, customer receipts, supplier payments, PPE purchases, loan movements and owner payments.'],['CRM and contracts','03 CRM Export Cleaned FINAL.xlsx · 04 Contracts Returns and Angry Customers.pdf','Completed August revenue €960,000, trade receivables €186,000 and September deposits.'],['Inventory and purchases','05 Warehouse Count Marta Notes.pdf · 06 Purchases Invoices and Goods Received.pdf','Physical count €143,000, damaged stock €22,000, purchases €459,000 and the count/flow reconciliation.'],['Payroll and assets','07 Payroll Bonuses Contractors NEW.xlsx · 08 Assets Repairs Leases Maybe.xlsx','Payroll categories, PPE additions €80,000, repair €10,000 and depreciation €24,000.'],['Debt, owner matters and legal','09 Loans Owner Card and Legal Problems.pdf','Loan €131,000, interest payable €2,000, distributions €110,000 and legal provision €25,000.'],['After-takeover confirmations','11 Evidence Received After Takeover.pdf','Corroborates R-17 impairment, damaged stock, legal exposure and inventory qualification.'],['Low-reliability context','10 Email and WhatsApp Dump DO NOT FORWARD.pdf','Explains management pressure; it does not create unsupported accounting amounts.']];
    return `<section class="page-heading"><p class="eyebrow">Source map</p><h2>Evidence register</h2><p>Every conclusion is linked to a concrete source. Missing insurance and opening-balance evidence are retained as gaps, not guessed.</p></section><section class="evidence-grid">${items.map(x=>`<article class="panel evidence-card"><p class="eyebrow">${x[0]}</p><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</section><section class="panel"><h3>Evidence standard used</h3><p>Bank, contractual completion, warehouse observations and after-takeover confirmations take priority. Management claims are not used when they conflict with those sources.</p></section>`;
  }

  function reconciliations(d) {
    return `${notice()}<section class="page-heading"><p class="eyebrow">Control environment</p><h2>Reconciliation controls</h2><p>“Conditional” means the calculation is visible but the underlying cause requires further evidence. It never means an unsupported journal was posted.</p></section><section class="reconciliation-grid">${d.reconciliations.map(r=>`<article class="panel reconciliation-card"><div class="control-title"><h3>${esc(r.name)}</h3>${badge(r.status)}</div><p>${esc(r.calculation)}</p>${r.difference===null||r.difference===undefined?'':`<p class="difference">Difference: ${eur(r.difference)}</p>`}</article>`).join('')}</section><section class="panel"><h3>Inventory control conclusion</h3><p>The primary statements reconcile at €112,000 inventory and €65,000 profit. If evidence proves the €121,000 count basis should replace it, COGS would be €396,000 and profit/equity/assets would each rise by €9,000 to €74,000 / €134,000 / €540,000. This is an alternative, not the current primary result.</p></section>`;
  }

  const correctionIds=new Set(['D057','D058','D059','D071','D072','D073','D074','D075']);
  const gapIds=new Set(['D034','D060','D075','D078','D097']);
  function effect(d) { if(['D043','D044'].includes(d.id)) return 'Original transaction: cash decreases and PPE increases by the same amount; total assets, profit and equity do not change at acquisition.'; if(['D071','D072','D073','D074'].includes(d.id)) return 'Closing estimate confirms an adjustment already recognised in the paired classification decision; no second effect is booked.'; const e=d.statementEffect; return `Profit ${eur(e.profit)} · Cash ${eur(e.cash)} · Total assets ${eur(e.assets)} · Liabilities ${eur(e.liabilities)} · Equity ${eur(e.equity)}`; }
  function flag(d) { return d.changedFromAI?'AI override recorded':correctionIds.has(d.id)?'review correction':gapIds.has(d.id)?'evidence gap':d.reviewTier==='material_judgment'?'material reviewed':'operational closed'; }
  function decisionRow(d) { return `<tr data-tier="${d.reviewTier}" data-confidence="${d.confidence}" data-flag="${flag(d)}"><td><b>${d.id}</b></td><td>${badge(d.reviewTier==='material_judgment'?'material':'operational')}</td><td>${esc(d.question)}</td><td>${esc(d.answer)}</td><td>${esc(d.evidence.join(' · '))}</td><td>${badge(d.confidence)}</td><td>${badge(flag(d))}</td></tr>`; }
  function trail(material) { return `<section class="metrics compact-metrics"><article class="metric-card"><span>Material decisions</span><strong>${material.length}</strong><small>full trail</small></article><article class="metric-card"><span>AI overrides</span><strong>${material.filter(d=>d.changedFromAI).length}</strong><small>none recorded</small></article><article class="metric-card warning"><span>Confidence profile</span><strong>${material.filter(d=>d.confidence==='high').length} / ${material.filter(d=>d.confidence==='medium').length} / ${material.filter(d=>d.confidence==='low').length}</strong><small>high / medium / low</small></article></section><section class="trail-list">${material.map(d=>`<details class="detail"><summary><b>${d.id}</b> · ${esc(d.answer)}</summary><div class="trail-grid"><div><b>Specific evidence</b><p>${esc(d.evidence.join(' · '))}</p></div><div><b>First AI proposal</b><p>${esc(d.aiProposal)}</p></div><div><b>Independent challenge</b><p>${esc(d.independentChallenge)}</p></div><div><b>Student reasoning</b><p>${esc(d.studentReasoning)}</p></div><div><b>Statement effect</b><p>${esc(effect(d))}</p></div><div><b>Review record</b><p>${d.changedFromAI?'Student override recorded.':'No student override recorded.'} Confidence: ${esc(d.confidence)}.</p></div></div></details>`).join('')}</section>`; }
  function decisions(d, review=false) { const list=review?d.decisions.filter(x=>x.reviewTier==='material_judgment'):d.decisions; const heading=review?'AI review trail':'Decision register'; const text=review?'Each material decision carries the AI proposal, independent challenge, student reasoning and exact statement effect.':'Filter the submitted decisions by tier, review condition and evidence confidence. The table reads directly from submission.json.'; return `${review?notice():''}<section class="page-heading"><p class="eyebrow">All ${review?'25 material':'100'} decisions</p><h2>${heading}</h2><p>${text}</p></section>${review?trail(list):`<div class="filter-bar"><button data-filter="all" class="selected">All 100</button><button data-filter="operational">Operational</button><button data-filter="material_judgment">Material</button><button data-filter="medium">Low confidence</button><button data-filter="evidence gap">Evidence gap</button><button data-filter="review correction">Review correction</button><button data-filter="AI override recorded">AI override</button><button data-filter="agent disagreement">Agent disagreement</button></div>${table('<tr><th>ID</th><th>Tier</th><th>Question</th><th>Certified answer</th><th>Specific evidence</th><th>Confidence</th><th>Review flag</th></tr>',list.map(decisionRow).join(''))}`}`; }
  function bindFilters(){document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('selected',x===b));const f=b.dataset.filter;document.querySelectorAll('tr[data-tier]').forEach(r=>r.hidden=!(f==='all'||r.dataset.tier===f||r.dataset.confidence===f||r.dataset.flag===f||(f==='agent disagreement'&&r.dataset.flag==='agent disagreement')))}));}
  function render(d){activeNav();let html=route==='/statements'?statements(d):route==='/schedules'?schedules(d):route==='/evidence'?evidence():route==='/reconciliations'?reconciliations(d):route==='/decisions'?decisions(d):route==='/review'?`${decisions(d,true)}${confirmation(d)}`:home(d);app.innerHTML=html;bindFilters();}
  const source = window.SUBMISSION_DATA ? Promise.resolve(window.SUBMISSION_DATA) : fetch('/submission.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`Submission data unavailable (${r.status})`);return r.json()});
  source.then(render).catch(e=>app.innerHTML=`<section class="panel"><h2>Case file unavailable</h2><p>${esc(e.message)}</p></section>`);
  window.addEventListener('hashchange', () => location.reload());
})();
